# Read more about client options at: https://github.com/kriswallsmith/Buzz/blob/master/doc/client.md
services:
    _defaults:
        public: false

    # Tell the auto wire system to use "FileGetContents" client as default client.
    # Set this to any of the other clients below (e.g. Curl or MultiCurl) to use a different default client.
    Buzz\Client\BuzzClientInterface: '@buzz.curl_client'

    # Clients
    buzz.file_get_contents_client:
        class: Buzz\Client\FileGetContents
        arguments:
            - timeout: 10

    buzz.curl_client:
        class: Buzz\Client\Curl
        arguments:
            - timeout: 10

    buzz.multi_curl_client:
        class: Buzz\Client\MultiCurl
        arguments:
            - timeout: 10

    # Browser
    Buzz\Browser:
        arguments: ['@Buzz\Client\BuzzClientInterface']