imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.yml }

framework:
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    templating:
        engines: ['twig']
        assets_base_url: "%assets_base_url%"

twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"

doctrine_couch_db:
    client:
        dbname: rfcwatch
    odm:
        auto_mapping: true
